server:
  port: 8001

spring:
  application:
    name: user-service

  # H2
  h2:
    console:
      enabled: true
      path: /h2-console

  # Datasource
  datasource:
    url: jdbc:h2:mem:user-service-db
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: update
